"""Entity descriptions for Tandem sensors (moved from const.py; research preserved)."""

from __future__ import annotations

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import EntityCategory, UnitOfMass, UnitOfTime

from .const import (
    ICON_ALERT_CIRCLE_OUTLINE,
    MGDL,
    MMOL,
    PERCENT,
    UNITS,
    TANDEM_SENSOR_KEY_ACTIVE_ALERTS_COUNT,
    TANDEM_SENSOR_KEY_ACTIVE_INSULIN,
    TANDEM_SENSOR_KEY_ACTIVE_PROFILE,
    TANDEM_SENSOR_KEY_ACTIVITY_MODE,
    TANDEM_SENSOR_KEY_AVG_GLUCOSE_MGDL,
    TANDEM_SENSOR_KEY_AVG_GLUCOSE_MMOL,
    TANDEM_SENSOR_KEY_BASAL_BOLUS_SPLIT,
    TANDEM_SENSOR_KEY_BASAL_LIMIT,
    TANDEM_SENSOR_KEY_BASAL_RATE,
    TANDEM_SENSOR_KEY_BATTERY_PERCENT,
    TANDEM_SENSOR_KEY_CARTRIDGE_INSULIN,
    TANDEM_SENSOR_KEY_CGM_HIGH_ALERT,
    TANDEM_SENSOR_KEY_CGM_LOW_ALERT,
    TANDEM_SENSOR_KEY_CGM_RATE_OF_CHANGE,
    TANDEM_SENSOR_KEY_CGM_SENSOR_DAYS_REMAINING,
    TANDEM_SENSOR_KEY_CGM_SENSOR_TYPE,
    TANDEM_SENSOR_KEY_CGM_SESSION_EXPIRY,
    TANDEM_SENSOR_KEY_CGM_SESSION_START,
    TANDEM_SENSOR_KEY_CGM_STATUS,
    TANDEM_SENSOR_KEY_CGM_USAGE,
    TANDEM_SENSOR_KEY_CLOSED_LOOP_PREFERRED,
    TANDEM_SENSOR_KEY_CONTROL_IQ_ENABLED,
    TANDEM_SENSOR_KEY_CONTROL_IQ_MODE,
    TANDEM_SENSOR_KEY_CONTROL_IQ_STATUS,
    TANDEM_SENSOR_KEY_CONTROL_IQ_TDI,
    TANDEM_SENSOR_KEY_CONTROL_IQ_WEIGHT,
    TANDEM_SENSOR_KEY_DAILY_BASAL_TOTAL,
    TANDEM_SENSOR_KEY_DAILY_BOLUS_COUNT,
    TANDEM_SENSOR_KEY_DAILY_BOLUS_TOTAL,
    TANDEM_SENSOR_KEY_DAILY_CARBS,
    TANDEM_SENSOR_KEY_ESTIMATED_INSULIN_REMAINING,
    TANDEM_SENSOR_KEY_GLUCOSE_CV,
    TANDEM_SENSOR_KEY_GLUCOSE_STD_DEV,
    TANDEM_SENSOR_KEY_GMI,
    TANDEM_SENSOR_KEY_HIGH_BG_THRESHOLD,
    TANDEM_SENSOR_KEY_IOB_HOURS,
    TANDEM_SENSOR_KEY_IOB_MINUTES,
    TANDEM_SENSOR_KEY_LASTSG_MGDL,
    TANDEM_SENSOR_KEY_LASTSG_MMOL,
    TANDEM_SENSOR_KEY_LASTSG_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_ALARM,
    TANDEM_SENSOR_KEY_LAST_ALERT,
    TANDEM_SENSOR_KEY_LAST_BG_READING,
    TANDEM_SENSOR_KEY_LAST_BOLUS_BG,
    TANDEM_SENSOR_KEY_LAST_BOLUS_CARBS,
    TANDEM_SENSOR_KEY_LAST_BOLUS_CORRECTION,
    TANDEM_SENSOR_KEY_LAST_BOLUS_FOOD,
    TANDEM_SENSOR_KEY_LAST_BOLUS_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_BOLUS_UNITS,
    TANDEM_SENSOR_KEY_LAST_CARBS,
    TANDEM_SENSOR_KEY_LAST_CARBS_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_CARTRIDGE_CHANGE,
    TANDEM_SENSOR_KEY_LAST_CARTRIDGE_FILL,
    TANDEM_SENSOR_KEY_LAST_MEAL_BOLUS,
    TANDEM_SENSOR_KEY_LAST_SITE_CHANGE,
    TANDEM_SENSOR_KEY_LAST_TUBING_CHANGE,
    TANDEM_SENSOR_KEY_LAST_UPLOAD,
    TANDEM_SENSOR_KEY_LOW_BG_THRESHOLD,
    TANDEM_SENSOR_KEY_LOW_INSULIN_ALERT,
    TANDEM_SENSOR_KEY_MAX_BOLUS,
    TANDEM_SENSOR_KEY_PREDICTED_GLUCOSE,
    TANDEM_SENSOR_KEY_PUMP_MODEL_INFO,
    TANDEM_SENSOR_KEY_PUMP_SERIAL_INFO,
    TANDEM_SENSOR_KEY_PUMP_SUSPENDED,
    TANDEM_SENSOR_KEY_PUMP_SUSPEND_REASON,
    TANDEM_SENSOR_KEY_RSSI,
    TANDEM_SENSOR_KEY_SG_DELTA,
    TANDEM_SENSOR_KEY_SOFTWARE_VERSION,
    TANDEM_SENSOR_KEY_TIME_ABOVE_RANGE,
    TANDEM_SENSOR_KEY_TIME_BELOW_RANGE,
    TANDEM_SENSOR_KEY_TIME_IN_RANGE,
    TANDEM_SENSOR_KEY_TOTAL_DAILY_INSULIN,
    TANDEM_SENSOR_KEY_UPDATE_TIMESTAMP,
)

# BLOOD_GLUCOSE_CONCENTRATION was added in HA 2024.11. Gracefully degrade so
# the descriptions import on older HA (null-not-guess: unknown -> None, not a fake class).
_BLOOD_GLUCOSE: SensorDeviceClass | None
try:
    _BLOOD_GLUCOSE = SensorDeviceClass.BLOOD_GLUCOSE_CONCENTRATION
except AttributeError:  # pragma: no cover
    _BLOOD_GLUCOSE = None

TANDEM_SENSORS_ALWAYS_AVAILABLE = (
    TANDEM_SENSOR_KEY_LASTSG_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_BOLUS_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_UPLOAD,
    TANDEM_SENSOR_KEY_UPDATE_TIMESTAMP,
    TANDEM_SENSOR_KEY_SOFTWARE_VERSION,
    TANDEM_SENSOR_KEY_PUMP_SERIAL_INFO,
    TANDEM_SENSOR_KEY_PUMP_MODEL_INFO,
    TANDEM_SENSOR_KEY_LAST_CARBS_TIMESTAMP,
    TANDEM_SENSOR_KEY_LAST_CARTRIDGE_CHANGE,
    TANDEM_SENSOR_KEY_LAST_SITE_CHANGE,
    TANDEM_SENSOR_KEY_LAST_TUBING_CHANGE,
    TANDEM_SENSOR_KEY_ACTIVE_PROFILE,
    TANDEM_SENSOR_KEY_CONTROL_IQ_ENABLED,
    TANDEM_SENSOR_KEY_CONTROL_IQ_WEIGHT,
    TANDEM_SENSOR_KEY_CONTROL_IQ_TDI,
    TANDEM_SENSOR_KEY_MAX_BOLUS,
    TANDEM_SENSOR_KEY_BASAL_LIMIT,
    TANDEM_SENSOR_KEY_CGM_HIGH_ALERT,
    TANDEM_SENSOR_KEY_CGM_LOW_ALERT,
    TANDEM_SENSOR_KEY_LOW_BG_THRESHOLD,
    TANDEM_SENSOR_KEY_HIGH_BG_THRESHOLD,
    TANDEM_SENSOR_KEY_LOW_INSULIN_ALERT,
    TANDEM_SENSOR_KEY_BATTERY_PERCENT,
    TANDEM_SENSOR_KEY_CGM_SENSOR_TYPE,
)

TANDEM_SENSORS = (
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LASTSG_MMOL,
        name="Last glucose level mmol",
        native_unit_of_measurement=MMOL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:water",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LASTSG_MGDL,
        name="Last glucose level mg/dl",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:water",
        entity_category=None,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LASTSG_TIMESTAMP,
        name="Last glucose update",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_SG_DELTA,
        name="Last glucose delta",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:plus-minus-variant",
        entity_category=None,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_RATE_OF_CHANGE,
        name="CGM rate of change",
        native_unit_of_measurement="mg/dL/min",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:trending-up",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_STATUS,
        name="CGM status",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon=ICON_ALERT_CIRCLE_OUTLINE,
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_UPDATE_TIMESTAMP,
        name="Last update",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_ACTIVE_INSULIN,
        name="Active insulin (IOB)",
        native_unit_of_measurement=UNITS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:water-alert",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_BASAL_RATE,
        name="Basal rate",
        native_unit_of_measurement="U/hr",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:chart-line",
        entity_category=None,
        suggested_display_precision=3,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_UNITS,
        name="Last bolus",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_TIMESTAMP,
        name="Last bolus time",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_MEAL_BOLUS,
        name="Last meal bolus",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:food",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_UPLOAD,
        name="Last pump upload",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:cloud-upload",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_AVG_GLUCOSE_MMOL,
        name="Average glucose level mmol",
        native_unit_of_measurement=MMOL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:chart-line",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_AVG_GLUCOSE_MGDL,
        name="Average glucose level mg/dl",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:chart-line",
        entity_category=None,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_TIME_IN_RANGE,
        name="Time in range",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon=None,
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_USAGE,
        name="CGM usage",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:percent",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CONTROL_IQ_STATUS,
        name="Control-IQ status",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:robot",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_SOFTWARE_VERSION,
        name="Software version",
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:code-tags",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_PUMP_SERIAL_INFO,
        name="Pump serial number",
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:identifier",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_PUMP_MODEL_INFO,
        name="Pump model",
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:code-tags",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    # ── Computed CGM summary sensors ───────────────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_GLUCOSE_STD_DEV,
        name="Glucose standard deviation",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:chart-bell-curve",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_GLUCOSE_CV,
        name="Glucose CV",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:chart-bell-curve-cumulative",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_GMI,
        name="GMI",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:diabetes",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_TIME_BELOW_RANGE,
        name="Time below range",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:arrow-down-bold",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_TIME_ABOVE_RANGE,
        name="Time above range",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:arrow-up-bold",
        entity_category=None,
        suggested_display_precision=1,
    ),
    # ── Event-derived sensors ──────────────────────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_ACTIVITY_MODE,
        name="Pump activity mode",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:run",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CONTROL_IQ_MODE,
        name="Control-IQ mode",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:robot",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_PUMP_SUSPENDED,
        name="Pump suspended",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:pause-circle",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_PUMP_SUSPEND_REASON,
        name="Pump suspend reason",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:pause-circle-outline",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_CARBS,
        name="Last carb entry",
        native_unit_of_measurement="g",
        state_class=None,
        device_class=None,
        icon="mdi:food-apple",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_CARBS_TIMESTAMP,
        name="Last carb entry time",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:clock",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_CARTRIDGE_CHANGE,
        name="Last cartridge change",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:cup-water",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_CARTRIDGE_FILL,
        name="Last cartridge fill amount",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_SITE_CHANGE,
        name="Last site change",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:needle",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_TUBING_CHANGE,
        name="Last tubing change",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:pipe",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CARTRIDGE_INSULIN,
        name="Cartridge insulin",
        native_unit_of_measurement=UNITS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:cup-water",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BG_READING,
        name="Last BG reading",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:blood-bag",
        entity_category=None,
        suggested_display_precision=0,
    ),
    # ── Computed insulin summary sensors ───────────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_TOTAL_DAILY_INSULIN,
        name="Total daily insulin",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_DAILY_BOLUS_TOTAL,
        name="Daily bolus total",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_DAILY_BASAL_TOTAL,
        name="Daily basal total",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:chart-line",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_BASAL_BOLUS_SPLIT,
        name="Basal percentage",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:chart-pie",
        entity_category=None,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_DAILY_CARBS,
        name="Daily carbs",
        native_unit_of_measurement="g",
        state_class=None,
        device_class=None,
        icon="mdi:food",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_DAILY_BOLUS_COUNT,
        name="Daily bolus count",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:counter",
        entity_category=None,
    ),
    # ── Pump settings sensors (from metadata.lastUpload.settings) ────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_ACTIVE_PROFILE,
        name="Active basal profile",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:account-cog",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CONTROL_IQ_ENABLED,
        name="Control-IQ enabled",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:robot",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CONTROL_IQ_WEIGHT,
        name="Control-IQ weight",
        native_unit_of_measurement=UnitOfMass.KILOGRAMS,
        state_class=None,
        device_class=SensorDeviceClass.WEIGHT,
        icon="mdi:weight-kilogram",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CONTROL_IQ_TDI,
        name="Control-IQ total daily insulin",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_MAX_BOLUS,
        name="Max bolus setting",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_BASAL_LIMIT,
        name="Basal rate limit",
        native_unit_of_measurement="U/hr",
        state_class=None,
        device_class=None,
        icon="mdi:speedometer",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=1,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_HIGH_ALERT,
        name="CGM high glucose alert",
        native_unit_of_measurement=MGDL,
        state_class=None,
        device_class=None,
        icon="mdi:alert-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_LOW_ALERT,
        name="CGM low glucose alert",
        native_unit_of_measurement=MGDL,
        state_class=None,
        device_class=None,
        icon=ICON_ALERT_CIRCLE_OUTLINE,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LOW_BG_THRESHOLD,
        name="Low BG alert threshold",
        native_unit_of_measurement=MGDL,
        state_class=None,
        device_class=None,
        icon=ICON_ALERT_CIRCLE_OUTLINE,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_HIGH_BG_THRESHOLD,
        name="High BG alert threshold",
        native_unit_of_measurement=MGDL,
        state_class=None,
        device_class=None,
        icon="mdi:alert-circle",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LOW_INSULIN_ALERT,
        name="Low insulin alert threshold",
        native_unit_of_measurement=UNITS,
        state_class=None,
        device_class=None,
        icon="mdi:battery-alert",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    # ── Alerts & Alarms sensors (Phase 2) ───────────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_ALERT,
        name="Last pump alert",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon=ICON_ALERT_CIRCLE_OUTLINE,
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_ALARM,
        name="Last pump alarm",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:alarm-light",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_ACTIVE_ALERTS_COUNT,
        name="Active pump alerts",
        native_unit_of_measurement=None,
        state_class=None,  # UNAVAILABLE in fallback paths — MEASUREMENT + None causes LTS gaps
        device_class=None,
        icon=ICON_ALERT_CIRCLE_OUTLINE,
        entity_category=None,
        suggested_display_precision=0,
    ),
    # ── Battery monitoring sensor (Phase 1 — level from events 9/34/35) ──
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_BATTERY_PERCENT,
        name="Pump battery level",
        native_unit_of_measurement=PERCENT,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.BATTERY,
        icon="mdi:battery",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=0,
    ),
    # ── Cheap wins: one-line reads of fields already on existing events ──
    SensorEntityDescription(
        # CGM transmitter signal strength (event 256 / 399). Raw pump value; the
        # unit/scale is not documented by Tandem, so no device_class/unit is claimed.
        key=TANDEM_SENSOR_KEY_RSSI,
        name="CGM signal strength",
        native_unit_of_measurement=None,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:signal",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_IOB_HOURS,
        name="Insulin on board (hours)",
        native_unit_of_measurement=UnitOfTime.HOURS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:timer-sand",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_IOB_MINUTES,
        name="Insulin on board (minutes)",
        native_unit_of_measurement=UnitOfTime.MINUTES,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:timer-sand",
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=0,
    ),
    SensorEntityDescription(
        # Control-IQ setting: whether closed-loop is preferred (bool True/False).
        key=TANDEM_SENSOR_KEY_CLOSED_LOOP_PREFERRED,
        name="Closed loop preferred",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:robot",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    # ── Phase 3: CGM sensor type (from event 313 AA_DAILY_STATUS) ────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_SENSOR_TYPE,
        name="CGM sensor type",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=None,
        icon="mdi:chip",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    # ── Phase 7: CGM sensor session / expiry (from events 212, 213, 214) ─
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_SESSION_START,
        name="CGM sensor session start",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:play-circle-outline",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_SESSION_EXPIRY,
        name="CGM sensor session expiry",
        native_unit_of_measurement=None,
        state_class=None,
        device_class=SensorDeviceClass.TIMESTAMP,
        icon="mdi:calendar-clock",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_CGM_SENSOR_DAYS_REMAINING,
        name="CGM sensor days remaining",
        native_unit_of_measurement="d",
        # Intermittently unavailable between sensor sessions — a MEASUREMENT
        # state_class with gaps causes LTS holes, so leave it None.
        state_class=None,
        device_class=None,
        icon="mdi:timer-sand",
        entity_category=None,
    ),
    # ── Phase 4: Bolus Calculator (from events 64, 65, 66) ────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_BG,
        name="Last bolus BG",
        native_unit_of_measurement=MGDL,
        state_class=None,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:water",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_CARBS,
        name="Last bolus carbs entered",
        native_unit_of_measurement="g",
        state_class=None,
        device_class=None,
        icon="mdi:food-apple",
        entity_category=None,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_CORRECTION,
        name="Last bolus correction",
        native_unit_of_measurement="U",
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=2,
    ),
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_LAST_BOLUS_FOOD,
        name="Last bolus food portion",
        native_unit_of_measurement="U",
        state_class=None,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=2,
    ),
    # ── PLGS & Daily Status (Phase 5) ─────────────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_PREDICTED_GLUCOSE,
        name="Predicted glucose",
        native_unit_of_measurement=MGDL,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=_BLOOD_GLUCOSE,
        icon="mdi:crystal-ball",
        entity_category=None,
        suggested_display_precision=0,
    ),
    # ── Estimated Remaining Insulin (Phase 6) ─────────────────────────
    SensorEntityDescription(
        key=TANDEM_SENSOR_KEY_ESTIMATED_INSULIN_REMAINING,
        name="Estimated insulin remaining",
        native_unit_of_measurement=UNITS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        icon="mdi:needle",
        entity_category=None,
        suggested_display_precision=1,
    ),
)
